name: seansanchez.Hackathon2021

on:
  workflow_dispatch:

jobs:
    build:
        name: Azure Pipeline
        runs-on: ubuntu-latest
        steps:
        - name: Azure Pipelines Action
          uses: Azure/pipelines@v1
          with:
            azure-devops-project-url: https://dev.azure.com/seansanchez/GitHub
            azure-pipeline-name: 'seansanchez.Hackathon2021'
            azure-devops-token: ${{ secrets.AZURE_DEVOPS_TOKEN }}